### ISSUE TITLE
Error 500 on delete 

### ISSUE THREAD

**Issue by SharkZekrom** [magrigry/jirai#5]
Hello ! j'ai trouvé un bug avec Jirai 🙂

On ne peut pas supprimer un post sans avoir supprimé avant les commentaires :c

[https://cdn.discordapp.com/attachments/625777292052004916/898332975807205496/Capture.PNG](url)

j'ai cliqué sur le bouton delete en haut a droite 🙂 

[https://cdn.discordapp.com/attachments/625777292052004916/898333127053836348/Capture.PNG](url)

mais si je clique sur le bouton en bas puis sur celui du dessus ça supprime correctement

**Comment by magrigry** [comment]
Solved in #bb3fde5
