### ISSUE TITLE
Volcano Theme - Jirai use default Azuriom icon instead of custom one

### ISSUE THREAD

**Issue by FireWolf-kPanel** [magrigry/jirai#7]
As you can see on this website : [https://eradium.cf/pickaxe](https://eradium.cf/pickaxe) the Jirai plugin use the default Azuriom icon instead of the one used by the index and every other pages ([https://eradium.cf](https://eradium.cf) for exemple)

Is this intended ? Is there any fix or it's just me ?

**Comment by magrigry** [comment]
Which icon ? A screenshot might help

**Comment by DarkShoro** [comment]
Nevermind, the issue resolved by itself.
